name: Release

on:
    push:
      tags:
        - 'v*'
    workflow_dispatch:

jobs:
    clojars:
        runs-on: ubuntu-latest
        environment: env
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - uses: DeLaGuardo/setup-clojure@12.5
              with:
                cli: "1.11.1.1139"
            - uses: actions/setup-node@v3
              with:
                node-version: "20"
            - name: Clojars release
              env:
                CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
                CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
              run: |
                npm ci && \
                npm run release && \
                clojure -T:dev:build clean  && \
                clojure -T:dev:build jar && \
                clojure -X:deploy-clojars
