name: Release

on:
    push:
      tags:
        - 'v*'
    workflow_dispatch:

jobs:
    clojars:
        runs-on: ubuntu-latest
        environment: release
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - uses: "DeLaGuardo/setup-clojure@12.5"
              with:
                cli: "1.11.1.1139"
            - name: release
              env:
                CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
                CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
              run: |
                npm ci && \
                npm run lib 
                
